Repository PvP-Club/server, pull requests merged in 2021-03, with the labels that each got.

#35 Change the color of (Owner) text
  pvp_club/init.lua
Labels: Test needed

#37 Add Score
  pvp_club/init.lua
Labels: Test needed

#38 Change numbers to strings and Fix chat command bugs in kills and deaths
  pvp_club/init.lua
Labels: Approved

#42 Set Player Default Health to 60
  pvp_club/init.lua
Labels: Approved

#41 Accept deaths for all death reasons
  CONTRIBUTING.md
  pvp_club/init.lua
Labels: Test needed

#36 Adds colored hotbar
  pvp_club/init.lua
  pvp_club/textures/pvp_club_hotbar_blue.png
  pvp_club/textures/pvp_club_hotbar_green.png
  pvp_club/textures/pvp_club_hotbar_red.png
  pvp_club/textures/pvp_club_hotbar_selected_blue.png
  pvp_club/textures/pvp_club_hotbar_selected_green.png
  pvp_club/textures/pvp_club_hotbar_selected_red.png
  pvp_club/textures/pvp_club_hotbar_selected_yellow.png
  pvp_club/textures/pvp_club_hotbar_yellow.png
Labels: Will be merged

#46 Add Default to Mod Dependencies
  pvp_club/mod.conf
Labels: Will be merged
