Repository PvP-Club/server, pull requests merged in 2021-02, with the labels that each got.

#5 5 players in 1 team
  pvp_club/init.lua
Labels: Approved

#9 /kills and /deaths Chat Commands
  pvp_club/init.lua
Labels: Enhancement, Review needed

#2 Color nametag of players
  color_nametags/init.lua
  color_nametags/mod.conf
Labels: Approved

#22 optimize chat commands
  pvp_club/init.lua
Labels: Approved

#25 Add (Owner) text in the nametag of owners
  pvp_club/init.lua
Labels: Approved

#27 Change the reason when player can't join
  pvp_club/init.lua
Labels: Approved, Before Start

#28 Disables pvp at spawn and adds spawn immunity
  pvp_club/init.lua
Labels: Approved

#29 Adds rplayer chatcommand and protection
  protector/README.md
  protector/admin.lua
  protector/depends.txt
  protector/description.txt
  protector/doors_chest.lua
  protector/hud.lua
  protector/init.lua
  protector/intllib.lua
  protector/license.txt
  protector/locale/de.po
  protector/locale/es.po
  protector/locale/fr.po
  protector/locale/it.po
  protector/locale/protector.de.tr
  protector/locale/protector.es.tr
  protector/locale/protector.fr.tr
  protector/locale/protector.it.tr
  protector/locale/protector.ru.tr
  protector/locale/protector.tr.tr
  protector/locale/ru.po
  protector/locale/template.pot
  protector/locale/tr.po
  protector/lucky_block.lua
  protector/mod.conf
  protector/pvp.lua
  protector/screenshot.png
  protector/settingtypes.txt
  protector/textures/default_chest_front.png
  protector/textures/default_chest_side.png
  protector/textures/default_chest_top.png
  protector/textures/doors_brown.png
  protector/textures/doors_grey.png
  protector/textures/doors_steel.png
  protector/textures/doors_steel_a.png
  protector/textures/doors_steel_b.png
  protector/textures/doors_trapdoor.png
  protector/textures/doors_trapdoor_side.png
  protector/textures/doors_trapdoor_steel.png
  protector/textures/doors_trapdoor_steel_side.png
  protector/textures/doors_wood.png
  protector/textures/doors_wood_a.png
  protector/textures/doors_wood_b.png
  protector/textures/johnsmith/protector_logo.png
  protector/textures/license.txt
  protector/textures/protector_display.png
  protector/textures/protector_logo.png
  protector/textures/protector_overlay.png
  protector/tool.lua
  pvp_club/init.lua
Labels: Approved

#30 Fix bug
  protector/init.lua
Labels: Approved

#32 Modify kill history
  pvp_club/init.lua
Labels: Approved

#33 Add sword
  pvp_club/init.lua
  pvp_club/textures/pc_sword.png
Labels: Approved

#34 Add red team and a member
  pvp_club/init.lua
Labels: Approved
